//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsOptimizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsOptimizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\runas]
        ///@=&quot;Take Ownership&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\runas\command]
        ///@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F&quot;
        ///&quot;IsolatedCommand&quot;=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string add_takeown {
            get {
                return ResourceManager.GetString("add_takeown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\Search&apos; -Name &apos;BackgroundAppGlobalToggle&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications&apos; -Name &apos;GlobalUserDisabled&apos; -value &apos;1&apos; -PropertyType DWORD -Force.
        /// </summary>
        internal static string bgapps {
            get {
                return ResourceManager.GetString("bgapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Control Panel\Desktop&apos; -Name &apos;WindowArrangementActive&apos; -value &apos;0&apos; -PropertyType String -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Personalization\Settings&apos; -Name &apos;AcceptedPrivacyPolicy&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack&apos; -Name &apos;ShowedToastAtLevel&apos; -value &apos;1&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy&apos; - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diagtrack {
            get {
                return ResourceManager.GetString("diagtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\System\GameConfigStore&apos; -Name &apos;GameDVR_FSEBehaviorMode&apos; -value &apos;00000002&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\SYSTEM\CurrentControlSet\Services\hidserv&apos; -Name &apos;Start&apos; -value &apos;00000004&apos; -PropertyType DWORD -Force.
        /// </summary>
        internal static string fullscroptdis {
            get {
                return ResourceManager.GetString("fullscroptdis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\System\GameConfigStore&apos; -Name &apos;GameDVR_FSEBehaviorMode&apos; -value &apos;00000000&apos; -PropertyType DWORD -Force
        ///.
        /// </summary>
        internal static string fullscropten {
            get {
                return ResourceManager.GetString("fullscropten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\System\GameConfigStore&apos; -Name &apos;GameDVR_Enabled&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\GameBar&apos; -Name &apos;UseNexusForGameBarEnabled&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\GameDVR&apos; -Name &apos;AudioCaptureEnabled&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\GameDVR&apos; -Name &apos;HistoricalCaptureEnabled&apos; -v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gamedvr {
            get {
                return ResourceManager.GetString("gamedvr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl&apos; -Name &apos;Win32PrioritySeparation&apos; -value &apos;00000016&apos; -PropertyType DWORD -Force.
        /// </summary>
        internal static string hex16 {
            get {
                return ResourceManager.GetString("hex16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl&apos; -Name &apos;Win32PrioritySeparation&apos; -value &apos;00000025&apos; -PropertyType DWORD -Force.
        /// </summary>
        internal static string hex25 {
            get {
                return ResourceManager.GetString("hex25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl&apos; -Name &apos;Win32PrioritySeparation&apos; -value &apos;00000026&apos; -PropertyType DWORD -Force.
        /// </summary>
        internal static string hex26 {
            get {
                return ResourceManager.GetString("hex26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl&apos; -Name &apos;Win32PrioritySeparation&apos; -value &apos;00000028&apos; -PropertyType DWORD -Force.
        /// </summary>
        internal static string hex28 {
            get {
                return ResourceManager.GetString("hex28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile&apos; -Name &apos;SystemResponsiveness&apos; -value &apos;00000000&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile&apos; -Name &apos;NetworkThrottlingIndex&apos; -value &apos;ffffffff&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games&apos; -Name &apos;Affinity&apos; -value &apos;00000000&apos; -PropertyT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mmcssreg {
            get {
                return ResourceManager.GetString("mmcssreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Control Panel\Mouse&apos; -Name &apos;MouseSpeed&apos; -value &apos;0&apos; -PropertyType STRING -Force
        ///New-Itemproperty -path &apos;HKCU:\Control Panel\Mouse&apos; -Name &apos;MouseThreshold1&apos; -value &apos;0&apos; -PropertyType STRING -Force
        ///New-Itemproperty -path &apos;HKCU:\Control Panel\Mouse&apos; -Name &apos;MouseThreshold2&apos; -value &apos;0&apos; -PropertyType STRING -Force
        ///New-Itemproperty -path &apos;HKCU:\Control Panel\Mouse&apos; -Name &apos;MouseSensitivity&apos; -value &apos;10&apos;
        ///New-Itemproperty -path &apos;HKCU:\Control Panel\Desktop&apos; -Name &apos;MouseWheelRouting&apos; -val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mousereg {
            get {
                return ResourceManager.GetString("mousereg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings&apos; -Name &apos;NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings&apos; -Name &apos;NOC_GLOBAL_SETTING_ALLOW_CRITICAL_TOASTS_ABOVE_LOCK&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\PushNotifications&apos; -Name &apos;ToastEnabled&apos; -value &apos;0&apos; -Propert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string notifreg {
            get {
                return ResourceManager.GetString("notifreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run&apos; -Name &apos;OneDrive&apos; -value &apos;0100000004077640378fd401&apos; -PropertyType Binary -Force.
        /// </summary>
        internal static string onedrivereg {
            get {
                return ResourceManager.GetString("onedrivereg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AccessibilityTemp&apos; -Name &apos;narrator&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Narrator\NoRoam&apos; -Name &apos;RunningState&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings&apos; -Name &apos;ShowHibernateOption&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string optregkeys {
            get {
                return ResourceManager.GetString("optregkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Language&quot;&apos; -Name &apos;Enabled&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\InputPersonalization&apos; -Name &apos;RestrictImplicitTextCollection&apos; -value &apos;1&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\InputPersonalization&apos; -Name &apos;RestrictImplicitInkCollection&apos; -value &apos;1&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\InputPers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string personreg {
            get {
                return ResourceManager.GetString("personreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///:: BatchGotAdmin
        ///:-------------------------------------
        ///REM  --&gt; Check for permissions
        ///&gt;nul 2&gt;&amp;1 &quot;%SYSTEMROOT%\system32\cacls.exe&quot; &quot;%SYSTEMROOT%\system32\config\system&quot;
        ///
        ///REM --&gt; If error flag set, we do not have admin.
        ///if &apos;%errorlevel%&apos; NEQ &apos;0&apos; (
        ///    echo Requesting administrative privileges...
        ///    goto UACPrompt
        ///) else ( goto gotAdmin )
        ///
        ///:UACPrompt
        ///    echo Set UAC = CreateObject^(&quot;Shell.Application&quot;^) &gt; &quot;%temp%\getadmin.vbs&quot;
        ///    set params = %*:&quot;=&quot;&quot;
        ///    echo UAC.ShellExecute &quot;cm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prefetchd {
            get {
                return ResourceManager.GetString("prefetchd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[-HKEY_CLASSES_ROOT\*\shell\runas]
        ///
        ///[-HKEY_CLASSES_ROOT\Directory\shell\runas].
        /// </summary>
        internal static string remove_takeown {
            get {
                return ResourceManager.GetString("remove_takeown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Software\Microsoft\TabletTip\1.7&apos; -Name &apos;EnableAutocorrection&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\TabletTip\1.7&apos; -Name &apos;EnableSpellchecking&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\TabletTip\1.7&apos; -Name &apos;EnableTextPrediction&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\TabletTip\1.7&apos; -Name &apos;EnablePredictionSpaceInsertion&apos; -value &apos;0&apos; -Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabettipreg {
            get {
                return ResourceManager.GetString("tabettipreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AccessibilityTemp&apos; -Name &apos;narrator&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKCU:\Software\Microsoft\Narrator\NoRoam&apos; -Name &apos;RunningState&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings&apos; -Name &apos;ShowHibernateOption&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uselessreg {
            get {
                return ResourceManager.GetString("uselessreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender&apos; -Name &apos;DisableAntiSpyware&apos; -value &apos;1&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender&apos; -Name &apos;DisableRoutinelyTakingAction&apos; -value &apos;1&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender&apos; -Name &apos;ServiceKeepAlive&apos; -value &apos;0&apos; -PropertyType DWORD -Force
        ///New-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Rea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string windefdis {
            get {
                return ResourceManager.GetString("windefdis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender&apos; -Name &apos;DisableAntiSpyware&apos; 
        ///Remove-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection&apos; -Name &apos;DisableAntiSpyware&apos; 
        ///Remove-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection&apos; -Name &apos;DisableRoutinelyTakingAction&apos; 
        ///Remove-Itemproperty -path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection&apos; -Name &apos;ServiceKeepAlive&apos; 
        ///Remove-It [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string windefen {
            get {
                return ResourceManager.GetString("windefen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set-Service AxInstSV -StartupType Disabled
        ///Set-Service bthserv -StartupType Disabled
        ///Set-Service dmwappushservice -StartupType Disabled
        ///Set-Service MapsBroker -StartupType Disabled
        ///Set-Service lfsvc -StartupType Disabled
        ///Set-Service SharedAccess -StartupType Disabled
        ///Set-Service lltdsvc -StartupType Disabled
        ///Set-Service NetTcpPortSharing -StartupType Disabled
        ///Set-Service PhoneSvc -StartupType Disabled
        ///Set-Service Spooler -StartupType Disabled
        ///Set-Service PrintNotify -StartupType Disabled
        ///Set-Serv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winsrvd {
            get {
                return ResourceManager.GetString("winsrvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set-Service AxInstSV -StartupType Enabled
        ///Set-Service bthserv -StartupType Enabled
        ///Set-Service dmwappushservice -StartupType Enabled
        ///Set-Service MapsBroker -StartupType Enabled
        ///Set-Service lfsvc -StartupType Enabled
        ///Set-Service SharedAccess -StartupType Enabled
        ///Set-Service lltdsvc -StartupType Enabled
        ///Set-Service NetTcpPortSharing -StartupType Enabled
        ///Set-Service PhoneSvc -StartupType Enabled
        ///Set-Service Spooler -StartupType Enabled
        ///Set-Service PrintNotify -StartupType Enabled
        ///Set-Service QWAVE - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winsrve {
            get {
                return ResourceManager.GetString("winsrve", resourceCulture);
            }
        }
    }
}
